### ISSUE TITLE
withdrawing netko from tokens.net

### ISSUE THREAD

**Issue by tzarebczan** [NetkoCoin/netko.tech#1]
What chain is it on now?

**Comment by cryptosi** [comment]
Netko has its own blockchain.  Withdraw Netko to either desktop wallet or other supported exchange. 

https://github.com/NetkoCoin/netko/releases/tag/v1.0

Bololex.com, Unnamed.exchange, Freiexchange, Yobit

**Comment by tzarebczan** [comment]
Why were we told to deposit to tokens.net for a swap? I guess that's not happening?
